name: doki8-checkin

on:
  workflow_dispatch:
    inputs:
      description:
        description: 'Manual triggers'
  schedule:
    - cron:  0 0 * * *  # 早上 8 点

jobs:
  checkin:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      SCKEY: ${{ secrets.SCKEY }}
      TG_TOKEN: ${{ secrets.TG_TOKEN }}
      TG_ID: ${{ secrets.TG_ID }}

    steps:
    - uses: actions/checkout@v2

    - name: Checkin
      run: |
        yarn
        node index.js